name: 'Unresolved Review Threads'

on:
  pull_request_review_comment:
    types: [edited, deleted]

  pull_request_review:
    types: [submitted, edited, dismissed]

  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize, review_requested, review_request_removed]
    branches:
      - dev

jobs:
  unresolvedReviewThreads:
    runs-on: ubuntu-latest
    steps:
      - uses: SamuelCabralCruz/unresolved-review-threads@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
